### ISSUE TITLE
No connection to localhost:8080

### ISSUE THREAD

**Issue by lodygens** [cyclone-project/cyclone-federation-provider#1]
Dear all,
I work on an Apple machine, so I have to use a virtual machine to run Docker, using Docker Quickstart Terminal. 
(At the bottom of this present, you can see what I did to follow you instructions)

When the container run, there is no service listening to port 8080

```
$ lsof | grep -i listen
```

> ssh-agent ...
> VBoxHeadl ...

If I modify the running VM to map port 8080 to 9990 (keycloak server)

```
$ lsof | grep -i listen
```

> ssh-agent  ...
> VBoxHeadl ...
> VBoxHeadl 51232 mboleg   20u    IPv4 0xe5ad00deb54592f3        0t0      TCP *:http-alt (LISTEN)

But still,  itl does not work
:(

Any help welcome,
Oleg

![idfedportmap](https://cloud.githubusercontent.com/assets/6367731/10020454/4211495a-6143-11e5-8339-107cbe7a6f64.png)

Here is what I did to follow your documentation

1) I have cloned

```
$ git clone https://github.com/cyclone-project/cyclone-federation-provider.git
```

2) I have build the docker image

```
$ docker build -t idfed-provider .
```

> Sending build context to Docker daemon 104.4 kB
> Step 0 : FROM java
> latest: Pulling from library/java
> 843e2bded498: Pull complete 
> 
> ...
> 
> Step 9 : EXPOSE 8080
>  ---> Running in d922e0fe92e9
>  ---> 0b550d211e7c
> Removing intermediate container d922e0fe92e9
> Successfully built 0b550d211e7c

```
$ docker images
```

> REPOSITORY          TAG                 IMAGE ID            CREATED              VIRTUAL SIZE
> idfed-provider      latest              0b550d211e7c        About a minute ago   1.327 GB

3) I run the container

```
$ docker run idfed-provider
```

> ...
> blabla
> ...
> 
> 13:34:09,212 INFO  [org.jboss.as](Controller Boot Thread) WFLYSRV0060: Http management interface listening on http://127.0.0.1:9990/management
> 13:34:09,217 INFO  [org.jboss.as](Controller Boot Thread) WFLYSRV0051: Admin console listening on http://127.0.0.1:9990
> 13:34:09,218 INFO  [org.jboss.as](Controller Boot Thread) WFLYSRV0025: Keycloak 1.5.0.Final (WildFly Core 1.0.1.Final) started in 22807ms - Started 307 of 526 services (274 services are lazy, passive or on-demand)

**Comment by mathiasslawik** [comment]
Hi Oleg,

I'll try to replicate your steps. For your testing, you could just use our predeployed Federation Provider at

https://federation.cyclone-project.eu

Best regards,
Mathias

**Comment by mathiasslawik** [comment]
You have to expose the "internal" port 8080 to a port on your Docker host by specifying the -p parameter, for example:

docker run -p 12345:8080 idfed-provider

would bind the 8080 port of the container to the 12345 port of your host.

**Comment by lodygens** [comment]
ok I’ll test that

it’s confusing because the port exposure is on the dockerfile: so I thought I wouldn’t have to do anything

**Comment by lodygens** [comment]
There is still something I don't get:

```
$ docker ps
```

> CONTAINER ID        IMAGE               COMMAND                  CREATED              STATUS              PORTS                     NAMES
> 2118b239a4a0        idfed-provider      "/opt/keycloak/bin/st"   About a minute ago   Up About a minute   0.0.0.0:32768->8080/tcp   silly_lovelace

```
$ docker port 2118b239a4a0
```

> 8080/tcp -> 0.0.0.0:32768

```
$> lsof| grep -i listen
```

ssh-agent   926 mboleg    3u    unix 0xe5ad00de9c644c93        0t0          /private/tmp/com.apple.launchd.y5FDSAgCUX/Listeners
VBoxHeadl 63348 mboleg   19u    IPv4 0xe5ad00deb2cffbc3        0t0      TCP localhost:58339 (LISTEN)

```
$ telnet localhost 8080
```

> Trying ::1...
> telnet: connect to address ::1: Connection refused
> Trying 127.0.0.1...
> telnet: connect to address 127.0.0.1: Connection refused
> telnet: Unable to connect to remote host

**Comment by lodygens** [comment]
Of course, I meant

```
$ telnet localhost 32768
```

> Trying ::1...
> telnet: connect to address ::1: Connection refused
> Trying 127.0.0.1...
> telnet: connect to address 127.0.0.1: Connection refused
> telnet: Unable to connect to remote host

**Comment by mathiasslawik** [comment]
You need to access the other port, e.g.:

telnet localhost 12345

**Comment by lodygens** [comment]
Yes, as in my last post
;)

**Comment by mathiasslawik** [comment]
I think it has to do with Mac OS and how you run Docker. I have never used it on Mac so I can just guess. 

I suppose you run Boot2Docker. Then you have to access the IP adress of the VirtualBox VM, and not localhost - in addition to using the -p option.

**Comment by lodygens** [comment]
No, I use "Docker Quickstart terminal" downloaded from docker.io

And yes, there must be something wrong with all that under Mac OS.

Under linux everything works well

**Comment by lodygens** [comment]
A last word: finally it works under Mac OS too.

The confusion came from the fact that we must not only publish the port with docker (using -p command line option), but also publish the port of the docker virtual machine, in VirtualBox.
