### ISSUE TITLE
Nuv.la authentication error with eduGain

### ISSUE THREAD

**Issue by cblanchet** [cyclone-project/cyclone-federation-provider#3]
Since the Cyclone federation provider was migrated to LAL infrastructure, I can neither sign in Cyclone nuvla nor in the Cyclone use cases portal with the eduGAIN authentication and my CNRS account identity.

The browser is redirected on 
1. federation.cyclone-project.eu -> OK
2. CNRS IdP -> OK
3 again the federation.cyclone-project.eu -> KO

The following error occurs on the page https://federation.cyclone-project.eu/samlbridge/module.php/saml/sp/saml2-acs.php/cyclone-saml-bridge

Catchable fatal error: Object of class DOMNodeList could not be converted to string in /var/simplesamlphp/modules/saml/lib/IdP/SAML2.php on line 703

**Comment by mathiasslawik** [comment]
This is related to a SimpleSAMLPHP ticket: https://github.com/simplesamlphp/simplesamlphp/issues/439

I added the following to `metadata/saml20-idp-hosted.php`:

```
'attributeencodings' => array(
  'eduPersonTargetedID' => 'raw',
  'urn:oid:1.3.6.1.4.1.5923.1.1.1.10' => 'raw',
),
```

Now its partially working, there are still some "Internal Error"s that could also be cause by me restarting the containers. Let's see if it works now.

**Comment by cblanchet** [comment]
Great !  it’s working again.

Thanks Mathias !

Christophe
