### ISSUE TITLE
Filtering field not working when selecting identity

### ISSUE THREAD

**Issue by bryan-brancotte** [cyclone-project/cyclone-federation-provider#4]
Hello

What ever your type in type filtering field (here lille, a french city) something happen, but not what we expect. Can we change its behavior to `.hide()` every identity that don't contain the specified string ?

![image](https://cloud.githubusercontent.com/assets/11556772/20258371/a442b806-aa4f-11e6-8666-29bda24c7692.png)

**Comment by bryan-brancotte** [comment]
Hi,
Fixing this issue would be greate
Best regards

**Comment by omer-ilhan** [comment]
Hi, we're using simplesamlphp's discopower module for this and depend on it for search as well so at the moment I'm not sure how much we can change there (or if we'll have to switch to a different module like the newer discojuice). Will have to look into it some more.

**Comment by omer-ilhan** [comment]
The update should have somewhat improved this issue. 
Can you confirm?

**Comment by bryan-brancotte** [comment]
works like a charm !
